function searchFlower() {
    // Get the input value
    var flowerName = document.getElementById('flowerInput').value.toLowerCase();

    // Object to store flower names and corresponding months
    var flowerMonths = {
        "chinese quince": "January",
        "daffodils": "January",
        "hazel": "January",
        "lesser celandine": "January",
        "lesser periwinkle": "January",
        "mexican fleabane": "January",
        "snowdrop": "January",
        "stinking hellebore": "January",
        "winter aconite": "January",
        "yellow crocus": "January",
        "alder": "February",
        "alexanders": "February",
        "cherry plum": "February",
        "early crocus": "February",
        "forsythia": "February",
        "yew": "February",
        "ash": "March",
        "blackthorn": "March",
        "bluebells": "March",
        "box": "March",
        "cherry laurel": "March",
        "common dog-violet": "March",
        "cowslip": "March",
        "elephant-ears": "March",
        "rape": "March",
        "rosemary": "March",
        "wallflower": "March",
        "wood anemone": "March",
        "wood spurge": "March",
        "bird's-eye primrose": "April",
        "blackberry": "April",
        "borage": "April",
        "californian poppy": "April",
        "cape daisy": "April",
        "common nettle": "April",
        "common sorrel": "April",
        "common vetch": "April",
        "foxglove": "April",
        "globeflower": "April",
        "hogweed": "April",
        "jerusalem sage": "April",
        "lady's mantle": "April",
        "purple iris": "April",
        "rowan": "April",
        "wood crane's bill": "April",
        "bird's-eye primrose": "May",
        "blackberry": "May",
        "borage": "May",
        "californian poppy": "May",
        "cape daisy": "May",
        "common nettle": "May",
        "common sorrel": "May",
        "common vetch": "May",
        "foxglove": "May",
        "globeflower": "May",
        "hogweed": "May",
        "jerusalem sage": "May",
        "lady's mantle": "May",
        "purple iris": "May",
        "rowan": "May",
        "wood crane's bill": "May",
        "butterfly bush": "June",
        "common poppy": "June",
        "common ragwort": "June",
        "common toadflax": "June",
        "common valerian": "June",
        "cornflower": "June",
        "evening primroses": "June",
        "field scabious": "June",
        "fuchsia": "June",
        "hollyhock": "June",
        "honeysuckle": "June",
        "pink": "June",
        "african lily": "July",
        "annual mercury": "July",
        "common fleabane": "July",
        "common sea-lavender": "July",
        "fennel": "July",
        "giant bellflower": "July",
        "goldenrod": "July",
        "heather": "July",
        "indian-bean-tree": "July",
        "love-lies-bleeding": "July",
        "mugwort": "July",
        "sneezewort": "July",
        "sunflower": "July",
        "tansy": "July",
        "tomato": "July",
        "virginia-creeper": "July",
        "wood sage": "July",
        "yellow loosestrife": "July",
        "cedar-of-lebanon": "August/September",
        "common reed": "August/September",
        "fig": "August/September",
        "ivy": "August/September",
        "japanese anemone": "August/September",
        "japanese knotweed": "August/September",
        "pampas-grass": "August/September",
        "strawberry-tree": "August/September",
        "cedar-of-lebanon": "October/November/December",
        "common reed": "October/November/December",
        "fig": "October/November/December",
        "ivy": "October/November/December",
        "japanese anemone": "October/November/December",
        "japanese knotweed": "October/November/December",
        "pampas-grass": "October/November/December",
        "strawberry-tree": "October/November/December",
        "chinese silver-grass": "October/November/December",
        "fatsia": "October/November/December",
        "gorse": "October/November/December",
        "japanese oregon-grape": "October/November/December",
        "winter jasmine": "October/November/December"
    };

    // Check if the flower is in the object
    if (flowerName in flowerMonths) {
        var month = flowerMonths[flowerName];
        alert("The flower '" + flowerName + "' is in bloom in " + month + ".");
    } else {
        alert("Sorry, the flower '" + flowerName + "' was not found in the wildflower calendar.");
    }
}